"""Shared parsing/config keys."""

PARSING_DEFAULT_KEY = "default"
PARSING_STRENGTH_COEFFICIENTS_KEY = "strength_coefficients"
PARSING_SKILL_DISCOVERY_CONFIG_KEY = "skill_discovery_config"
PARSING_JUNK_KEYWORDS_KEY = "junk_keywords"
PARSING_STOPWORDS_KEY = "stopwords"
PARSING_MIN_TERM_LENGTH_KEY = "min_term_length"
PARSING_MAX_DISCOVERY_TERMS_KEY = "max_discovery_terms"
PARSING_GOVERNMENT_DISCOVERY_PATTERNS_KEY = "government_discovery_patterns"
PARSING_GOVERNMENT_DISCOVERY_CONFIG_KEY = "government_discovery_config"
PARSING_GOVERNMENT_TERMS_KEY = "government_terms"
PARSING_TRUSTED_DESCRIPTION_SOURCES_KEY = "trusted_description_sources"
PARSING_CLEARANCE_NORMALIZATION_KEY = "clearance_normalization"
PARSING_APS_PATTERN_KEY = "aps"
PARSING_EL_PATTERN_KEY = "el"
PARSING_CLEARANCE_PATTERN_KEY = "clearance"
PARSING_DEPARTMENT_PATTERN_KEY = "department"
