"""Shared schema and learning vocabulary."""


SIGNAL_NAME_KEY = "name"
SIGNAL_LABEL_KEY = "label"
SIGNAL_FIT_LABEL_KEY = "fit_label"
SIGNAL_WATCHOUT_LABEL_KEY = "watchout_label"
SIGNAL_RISK_LABEL_KEY = "risk_label"
SIGNAL_ALIASES_KEY = "aliases"
SIGNAL_ALIAS_HITS_KEY = "alias_hits"
SIGNAL_SNIPPET_HITS_KEY = "snippet_hits"
SIGNAL_DOMINANCE_LEVEL_KEY = "dominance_level"
SIGNAL_ALIGNMENT_KEY = "alignment"
SIGNAL_ADJUSTMENT_KEY = "adjustment"

LEARNING_SIGNAL_KEY = "signal"
LEARNING_NORMALIZED_KEY = "normalized_key"
LEARNING_ORIGINAL_TEXTS_KEY = "original_texts"
LEARNING_CATEGORY_KEY = "category"
LEARNING_SOURCE_KEY = "source"
LEARNING_CONTEXT_KEY = "context"
LEARNING_CONTEXT_TERMS_KEY = "context_terms"
LEARNING_EVIDENCE_KEY = "evidence"
LEARNING_NEEDS_REVIEW_KEY = "needs_review"
LEARNING_KNOWLEDGE_MATCH_KEY = "knowledge_match"
LEARNING_CONFIDENCE_KEY = "confidence"
LEARNING_NOTES_KEY = "notes"
LEARNING_SUGGESTED_CATEGORY_KEY = "suggested_category"
LEARNING_SUGGESTED_VALUES_KEY = "suggested_values"
LEARNING_HISTORY_KEY = "history"

COMPETITIVE_SIGNALS_KEY = "competitive_signals"
HARD_BLOCK_REASONS_KEY = "hard_block_reasons"
TITLE_REASON_KEY = "title_reason"

CATEGORY_CAPABILITY_CONCEPT = "capability_concept"
CATEGORY_GOVERNMENT_CONTEXT = "government_context"
CATEGORY_GOVERNMENT_CONTEXT_PATTERN = "government_context_pattern"
CATEGORY_JOB_TYPE_NORMALIZATION_CANDIDATE = "job_type_normalization_candidate"
CATEGORY_ROLE_TITLE_TOKEN = "role_title_token"
CATEGORY_ROLE_TITLE_PATTERN = "role_title_pattern"
CATEGORY_TITLE_NORMALIZATION_CANDIDATE = "title_normalization_candidate"
CATEGORY_HARD_BLOCKER_PATTERN = "hard_blocker_pattern"
CATEGORY_CV_FARMING_PATTERN = "cv_farming_pattern"
CATEGORY_PROFILE_SECTION_LABEL = "profile_section_label"
VALID_SIGNAL_CATEGORIES = frozenset({
    CATEGORY_CAPABILITY_CONCEPT,
    CATEGORY_GOVERNMENT_CONTEXT,
    CATEGORY_GOVERNMENT_CONTEXT_PATTERN,
    CATEGORY_JOB_TYPE_NORMALIZATION_CANDIDATE,
    CATEGORY_ROLE_TITLE_TOKEN,
    CATEGORY_ROLE_TITLE_PATTERN,
    CATEGORY_TITLE_NORMALIZATION_CANDIDATE,
    CATEGORY_HARD_BLOCKER_PATTERN,
    CATEGORY_CV_FARMING_PATTERN,
    CATEGORY_PROFILE_SECTION_LABEL,
})

PATTERN_SIGNAL_CATEGORIES = frozenset({
    CATEGORY_ROLE_TITLE_PATTERN,
    CATEGORY_GOVERNMENT_CONTEXT_PATTERN,
})

SOURCE_JOB_PARSING = "job parsing"
SOURCE_CV_PARSING = "CV parsing"

ALIGNMENT_STRONG = "strong"
ALIGNMENT_PARTIAL = "partial"
ALIGNMENT_WEAK = "weak"
VALID_ALIGNMENT_VALUES = frozenset({
    ALIGNMENT_STRONG,
    ALIGNMENT_PARTIAL,
    ALIGNMENT_WEAK,
})

LEARNING_STATUS_APPROVED = "approved"
LEARNING_STATUS_IGNORED = "ignored"
LEARNING_STATUS_PENDING = "pending"

TITLE_REASON_POTENTIAL_MATCH = "TITLE_POTENTIAL_MATCH"

OBSERVATION_SKILL_KEY = "skill"
HARD_BLOCK_TEXT_KEY = "text"

MANAGED_KNOWLEDGE_KIND_KEY = "kind"
MANAGED_KNOWLEDGE_NAME_KEY = "name"
MANAGED_KNOWLEDGE_VERSION_KEY = "version"
MANAGED_KNOWLEDGE_UPDATED_AT_KEY = "updated_at"
MANAGED_KNOWLEDGE_DESCRIPTION_KEY = "description"
MANAGED_KNOWLEDGE_ENTRIES_KEY = "entries"
MANAGED_KNOWLEDGE_VALUE_KEY = "value"
MANAGED_KNOWLEDGE_ALIASES_KEY = "aliases"
MANAGED_KNOWLEDGE_LABEL_KEY = "label"
MANAGED_KNOWLEDGE_TERMS_KEY = "terms"
